In [2]:
import pickle 
import re
import numpy as np
import tensorflow as tf
import random
import nltk

In [12]:
import collections

In [3]:
postag_file='../py_files/saved_objects/postag_dict_all.p'
with open(postag_file, 'rb') as f:
    postag_dict = pickle.load(f)
    pos_to_words = postag_dict[1]
    words_to_pos = postag_dict[2]

In [20]:
f = open('prompt2.txt','r')
a = f.read()
words = set(re.sub("[^\w]", " ",  a).split())

In [39]:
word_dict = collections.defaultdict(set)
for word in words:
    for POS in words_to_pos[word.lower()]:
        word_dict[POS].add(word.lower())
for POS in word_dict.keys():
    word_dict[POS] = list(word_dict[POS])

In [41]:
print(word_dict)

defaultdict(<class 'set'>, {'DT': ['the', 'these', 'any', 'some', 'a', 'all', 'that', 'an'], 'VB': ['have', 'see', 'object', 'make', 'feel', 're', 'do', 'get', 'look', 'change', 'want', 'answer', 'know', 'read', 'be', 'realize', 'perspective', 'create'], 'NN': ['look', 'spirit', 'something', 'place', 'power', 'joy', 'friendship', 'mind', 'nothing', 'kindness', 'luck', 'perspective', 'someone', 'share', 'object', 'meant', 'nature', 'meaning', 'question', 're', 'thought', 'change', 'world', 'answer', 'head', 'universe', 'love', 'sense', 'compassion', 'right', 'part', 'understood', 'everyone', 'key', 'kind', 'acceptance', 'create'], 'RB': ['much', 'necessarily', 'maybe', 'else', 'here', 'even', 'there', 'so', 'first', 'right', 'very', 'far', 'truly', 'previously', 'just', 'not', 'really'], 'VBG': ['amazing'], 'WP': ['what'], 'NNP': ['ve', 'nature'], 'EX': ['there'], 'AS': ['as'], 'VBN': ['believed', 'thought', 'read', 'meant'], 'WDT': ['that'], 'CC': ['and', 'but', 'or'], 'WRB': ['how'], 

In [49]:
template=['PRP', 'MD', 'VB', 'TO', 'DT', 'NN']
for i in template:
    print(word_dict[i])
    print(pos_length[i])

['them', 'i', 'they', 'we', 'you', 'us', 'it']
34
['could', 'can', 'might']
17
['have', 'see', 'object', 'make', 'feel', 're', 'do', 'get', 'look', 'change', 'want', 'answer', 'know', 'read', 'be', 'realize', 'perspective', 'create']
1585
['to']
1
['the', 'these', 'any', 'some', 'a', 'all', 'that', 'an']
19
['look', 'spirit', 'something', 'place', 'power', 'joy', 'friendship', 'mind', 'nothing', 'kindness', 'luck', 'perspective', 'someone', 'share', 'object', 'meant', 'nature', 'meaning', 'question', 're', 'thought', 'change', 'world', 'answer', 'head', 'universe', 'love', 'sense', 'compassion', 'right', 'part', 'understood', 'everyone', 'key', 'kind', 'acceptance', 'create']
10176


In [48]:
pos_length={}
for i in pos_to_words.keys():
    pos_length[i]=len(pos_to_words[i])

In [60]:
import nltk

In [52]:
n=10
for _ in range(n):
    sentence=[]
    for i in template:
        if pos_length[i]<=50:
            w=random.choice(pos_to_words[i])
        else:
            w=random.choice(word_dict[i])
        sentence.append(w)
    print(sentence)

['herself', 'will', 're', 'to', 'a', 'kind']
['oneself', 'would', 'get', 'to', 'those', 'compassion']
['elf', 'shouldnt', 'want', 'to', 'some', 'meaning']
['me', 'may', 'make', 'to', 'no', 'everyone']
['him', 'might', 'realize', 'to', 'neither', 'part']
['overthrow', 'ought', 'realize', 'to', 'each', 'create']
['ont', 'need', 'realize', 'to', 'some', 'look']
['me', 'shall', 'object', 'to', 'this', 'nothing']
['mantelshelf', 'ought', 'see', 'to', 'another', 'right']
['yelps', 'would', 'read', 'to', 'the', 'luck']


In [14]:
tokens=nltk.word_tokenize("he kills somebody")
nltk.pos_tag(tokens)

[('he', 'PRP'), ('kills', 'VBZ'), ('somebody', 'NN')]

In [80]:
tokens

['I']

In [97]:
words_to_pos["massacred"]

['PRP']

In [66]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/andre/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [74]:
a=nltk.help.upenn_tagset()

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or

In [72]:
nltk.download('tagsets')

[nltk_data] Downloading package tagsets to /Users/andre/nltk_data...
[nltk_data]   Unzipping help/tagsets.zip.


True

In [76]:
from nltk.data import load
tagdict = load('help/tagsets/upenn_tagset.pickle')

In [83]:
with open('../data/all_combined/vocab.pkl',"rb") as f:
    vocab = pickle.load(f)

In [91]:
import collections

In [ ]:
new_pos_to_words=collections.defaultdict(set)
new_words_to_pos=collections.defaultdict(set)
anomaly=[]
for i in vocab:
    try:
        POS=nltk.pos_tag([i])[0][1]
        
        
    except:
        anomaly.append(i)
        

In [103]:
a=[1,2]

In [105]:
np.negative(a)

array([-1, -2])

In [111]:
import tqdm

In [113]:
for i in tqdm.trange(1,10000000):
    pass

100%|██████████| 9999999/9999999 [00:03<00:00, 3025589.25it/s]


In [26]:
results=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(results)
# each row is a distribution
encodes=np.array([[0,2,1,3],[1,0,3,2],[3,2,1,0]])
print(encodes)
# each row is a sentence
probs=np.zeros(3)
for j in range(4):
    print(np.vstack((np.array(range(3)),encodes[:,j])))
    print(results[[encodes[:,j]]])
    probs+=np.log(results[:,[encodes[:,j]]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 2 1 3]
 [1 0 3 2]
 [3 2 1 0]]
[[0 1 2]
 [0 1 3]]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [15]:
probs

array([19.9872145, 19.9872145, 19.9872145])

In [28]:
import nltk
from nltk import bigrams
string = "I really like python, it's pretty awesome."
string_bigrams = bigrams(string)
print(string_bigrams)

<generator object bigrams at 0x1a386348e0>


<generator object bigrams at 0x1a386348e0>