In [4]:
postag_file='../py_files/saved_objects/postag_dict_all.p'
with open(postag_file, 'rb') as f:
    postag_dict = pickle.load(f)
    pos_to_words = postag_dict[1]
    words_to_pos = postag_dict[2]

In [17]:
import numpy as np

In [13]:
import tensorflow as tf

In [12]:
words_to_pos["buffalo"]

['NN', 'NNS', 'NNP']

In [22]:
a="He had become one of the richest men in Italy, and all he had to do was stay in the city, not buy, because he loved to sit and cry that he could get away withthat, but he had to deal with people.And she told that father that if he went out too far they would beat him up and kill him. All that was needed was to kill him.His father's reaction was a kind of rage.But the story goes in a different way.The man started to cry, and everyone around him started to cry. At first, he just laughed.Suddenly, the father's anger was growing stronger.The boy stared at him, his head bowed in his arms. The only emotion he could really understand was that his father was trying his best to keep his eyes clear.At first, he was shocked, but he kept trying his best to make it look like it was going smoothly."

In [45]:
a=np.array([[1,2,3],[3,4,5]])

In [49]:
a=tf.cast(a,tf.float32)
b=tf.nn.softmax(a)
with tf.Session() as sess:
    c=sess.run(b)
print(c)
np.sum(c,axis=1)

[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]


array([1., 1.], dtype=float32)

In [24]:
import re

In [30]:
words = set(re.sub("[^\w]", " ",  a).split())

In [31]:
wordbank={}
for w in words:
    for k in words_to_pos[w]:
        if k not in wordbank.keys():
            wordbank[k]=[]
        wordbank[k].append(w)

In [43]:
print(wordbank["JJ"])

['different', 'clear', 'first']


In [33]:
import random

In [34]:
template=['PRP', 'VBD', 'CD', 'JJ', 'NN', 'IN', 'DT', 'JJ', 'NN', 'IN', 'NN', 'IN', 'PRP$', 'NN']

In [40]:
n=10
for _ in range(n):
    sentence=[]
    for i in template:
        w=random.choice(wordbank[i])
        sentence.append(w)
    print(sentence)

['she', 'kept', 'one', 'different', 'emotion', 'because', 'the', 'clear', 'father', 'that', 'stay', 'at', 'his', 'deal']
['she', 'told', 'one', 'first', 'look', 'if', 'the', 'different', 'way', 'in', 'look', 'that', 'his', 'emotion']
['he', 'told', 'one', 'clear', 'deal', 'if', 'that', 'first', 'story', 'if', 'kind', 'of', 'his', 'story']
['it', 'started', 'one', 'clear', 'anger', 'that', 'the', 'clear', 'beat', 'with', 'stay', 'because', 'his', 'sit']
['she', 'stared', 'one', 'clear', 'reaction', 'in', 'that', 'different', 'head', 'of', 'man', 'with', 'his', 'head']
['she', 'stared', 'one', 'clear', 'father', 'because', 'the', 'first', 'richest', 'if', 'city', 'with', 'his', 'richest']
['he', 'told', 'one', 'clear', 'boy', 'because', 'a', 'first', 'rage', 'in', 'sit', 'because', 'his', 'story']
['they', 'told', 'one', 'different', 'man', 'like', 'that', 'first', 'anger', 'if', 'man', 'if', 'his', 'stay']
['she', 'bowed', 'one', 'clear', 'richest', 'if', 'that', 'clear', 'kind', 'in', 

In [37]:
sentence

['it',
 'kept',
 'one',
 'different',
 'story',
 'if',
 'the',
 'first',
 'cry',
 'because',
 'man',
 'because',
 'his',
 'deal']